version: '3'

services:
    # dev:
    #     container_name: nestjs_api_dev
    #     image: nestjs-api-dev:1.0.0
    #     build:
    #         context: .
    #         dockerfile: ./Dockerfile
    #     command: npm run start:debug
    #     ports:
    #         - 3000:3000
    #     networks:
    #         - nesjs-network
    #     volumes:
    #         - './src:/app/src'
    #     restart: unless-stopped
    #     environment:
    #         - DB_URL=mongodb://db_mongo
    #     depends_on:
    #         - db
    db:
        image: mongo:latest
        container_name: db_mongo
        volumes:
          - mongodata:/data/db
        environment:
          - MONGODB_DATABASE="thai"
        ports:
          - "27017:27017"
volumes:
  mongodata:
networks:
    nesjs-network: